### PR TITLE
Added user information and tags to notice email

### PR DESCRIPTION
**Pull request by laughinggoose**
For #177 

This pull request is incomplete. I wanted to get feedback on the new plain text email before I copied the changes to the HTML email.

Here is the plain text output with user info:

> A new  critical  event has occurred in the "Testing" project.
> 
> Tags:
> important, web
> 
> 
> User's Name:
> First Last
> 
> 
> User's Identity:
> firstylaster
> 
> 
> User's Email:
> useremail@domain.com
> 
> 
> User's Description:
> A person
> 
> 
> View the event:
> http://localhost:50000/event/1

### CODE REVIEW

**Comment by niemyjski** [comment]
Thanks for this, We'll take a look at this and get it merged soon.

**Comment by ejsmith** [comment]
I like it! I am thinking we should collapse the user information down into a single line though. It's probably pushing important content down out of view.

Not sure if we need the users description. If we do want it, we can hide that section if their description is empty.

**Comment by laughinggoose** [comment]
@ejsmith How would you condense the user information into a single line? What if one of the user fields are missing?

The user's description was mentioned specifically in #136. I'm not sure what is though really. I don't think we set this for our users.

**Comment by ejsmith** [comment]
So for user we just have identity and name:
https://github.com/exceptionless/Exceptionless.Net/blob/master/src/Exceptionless/Models/Client/Data/UserInfo.cs

The user description is where the user can type in a description of what happened for an error after the error occurs. So I think we can include that if it is populated which is not very often. So maybe something like this:

Tags:
important, web

User:
name (identity)

User's Description:
I was trying to place an order.

**Comment by niemyjski** [comment]
@laughinggoose Is this pr complete?

**Comment by laughinggoose** [comment]
Not yet. I still need to update the text email with Eric's feedback and then port it to the HTML email.

**Comment by niemyjski** [comment]
@laughinggoose I'm going to close this until it's ready. Can you please reopen a pr when it's finished.

**Pull request closed without merging**
